-- 1. select * from items order by price ASC;
-- 2. select * from items where price >=80 order by price DESC;
-- 3. select lastname, firstname from customers order by lastname ASC;
-- 4. select lastname from customers order by lastname DESC;
